### PR TITLE
Fix for Cocoapods v1.8.1

### PR DESCRIPTION
**Pull request by torfinnberset**
Closes #36

* Fixed issue where wrong source was used.
* Updated version to v1.0.4
* Updated gemspec to bundler v2.0.2
* Added Gemfile.lock

With special thanks to @Tripwire999 ;)

### CODE REVIEW

**Comment by eyalbe4** [comment]
@torfinnberset,
Will you be able to sign the CLA?

**Comment by torfinnberset** [comment]
@eyalbe4 I already have signed, as I've also contributed to conan before

**Comment by torfinnberset** [comment]
@eyalbe4 I noticed it was a different form than Conan, so I signed it again just now

**Comment by eyalbe4** [comment]
Thanks @torfinnberset.
We'll publish the release soon.

**Comment by torfinnberset** [comment]
Looking forward to it :)

**Comment by eyalbe4** [comment]
Version 1.0.4 is published.
Thank you @torfinnberset and @Tripwire999!

**Pull request merged**
