### PR TITLE
fix pod install failed when Podfile.lock exists

### PR DESCRIPTION
**Pull request by SomnusLee1988**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@SomnusLee1988 - thank you for creating this fix!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by SomnusLee1988** [comment]
OK, I have signed JFrog's CLA. What else do I need to do?

**Comment by eyalbe4** [comment]
Thanks @SomnusLee1988!

Before we publish the new version, can you pease test and confirm that after building the code, everything works as expected?
You can do this as follows:
1. ```git clone https://github.com/jfrog/cocoapods-art.git```
2. ```cd cocoapods-art```
3. ```gem build cocoapods_art.gemspec```
4. ```gem install gen install cocoapods-art-1.0.3.gem```
5. See that the new version works as expected.

Thanks!

**Comment by PoissonBallon** [comment]
Any news about it ? I can help ?

**Comment by NirPernexus** [comment]
Yeah, I have the same issue as well. Would be great if fixed!

**Comment by omuntis** [comment]
Thank you for the fix.
I tried 1.0.3 out and it fixed the `pod install` issue, but `pod update` still doesn't work.
It delivers `[!] Unable to find a specification for <any pod>`

**Comment by NirPernexus** [comment]
Any update on this? For the past month, my team has had to delete Podfile.lock everytime they need to update the pods. Would be really great to not have to do this.

**Comment by eyalbe4** [comment]
@omuntis and @NirPernexus,
We couldn't reproduce the **pod update** issue with version 1.0.3.
Can you please share a sample project and relevant steps so that we can see the issue?
We've also just [published](https://rubygems.org/gems/cocoapods-art) version 1.0.3

**Comment by NirPernexus** [comment]
Thanks, I updated to 1.0.3 but still have the issue. I'm sure you understand that I can't post source code from my employer. I'll consider creating an empty test project, that showcases the error.
A different option would be to give you the console log, from when I get the error.
Finally, this might turn out to be a Cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/8540

**Comment by seanliu1** [comment]
In my case, it runs well in my local machine, however in the ci. 
I tried to

```
echo -e "machine quibi.jfrog.io\nlogin ${JFROG_USERNAME}\npassword ${JFROG_PASSWORD}" > ~/.netrc

bundle exec pod repo-art add cocoapods-local "https://xxxxx/api/pods/cocoapods-local"
```

I will see `sh: line 0: cd: /Users/distiller/.cocoapods/repos: No such file or directory`

Since this step is run before pod install. 

I wonder what is the order for it. It looks like when we run pod install first, it will still fail because we have not add cocoapods-local. If we do cocoapods-local first, then cocoapods/repos is not existed. Unless we manually create it

**Pull request merged**
