### PR TITLE
Added env variable with custom location of .netrc file

### PR DESCRIPTION
**Pull request by lursk**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@lursk - thank you for this!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by lursk** [comment]
Done.

**Comment by eyalbe4** [comment]
Thanks @@lursk.
With which name did you sign the CLA? Your github details include only **@lursk**.

**Comment by lursk** [comment]
@eyalbe4 Oh, sorry. I've updated my profile info.

**Comment by eyalbe4** [comment]
Merged @lursk,
Before we release this, will you be able to build the sources from the master branch and confirm that all works as expected?
Thanks

**Comment by lursk** [comment]
As I can see, it's working as expected on `jfrog:master` branch.

**Comment by eyalbe4** [comment]
@lursk - version 1.0.2 is released.
Thanks again for this!

**Pull request merged**
