### PR TITLE
netrc optional change

### PR DESCRIPTION
**Pull request by marchinram**
Clone of https://github.com/JFrogDev/cocoapods-art/pull/12 
Working with employer to get CLA signed should hopefully have this early next week

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks @marchinram.
Please let us know when the [CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) is signed and we'll merge this.

**Comment by marchinram** [comment]
@eyalbe4 I got approval for this, however the person who will sign cla may have different email than mine, is that ok?

**Comment by marchinram** [comment]
@eyalbe4 The CLA has been signed, the signer's name is Matt Kamen, did you receive? Or does it need to be manually sent?

**Comment by eyalbe4** [comment]
@marchinram,
I'm afraid the CLA must be signed with the same github email address and name of the committer...
You can either ask the person who signed the CLA to submit a new pull request or sign the CLA.

**Comment by marchinram** [comment]
@eyalbe4 I signed CLA do you receive automatically or do I need to email you?

**Comment by eyalbe4** [comment]
Thanks @marchinram.
We'll soon publish a new release.

**Comment by eyalbe4** [comment]
**cocoapods-art 1.0.1** is has been published.

**Comment by kylefowler** [comment]
hey @eyalbe4. Thanks for merging this. We realized after the merge that this only solved the first half of the issue which was pulling the podspecs from artifactory. We didn't realize that the artifactory server was the one putting in the `source` line to the podspec and at that point it doesnt include any credentials. So now `pod install` is failing because the source file doesnt have the authentication information that was now added in the repo add step.

The solution seems to be modifying the source line of the downloaded podspec and including the credentials from the stored repo url. I cant decide if that feels hacky or necessary. Any thoughts?

**Comment by eyalbe4** [comment]
Hi @kylefowler,
Question: Can you store the credentials in the *.netrc* file, as shown in the [README](https://github.com/JFrogDev/cocoapods-art/blob/master/README.md)?

**Comment by kylefowler** [comment]
I personally could yeah, we were just trying to avoid the .netrc file since we are distributing the pod in question to external parties. The .netrc file seemed like an excessive step to request that they modify their environment outside of the project workspace for this to work. It definitely appears as if it will be the only solution for now.

**Pull request merged**
