### PR TITLE
[BUG FIX] Move to using netrc-optional for curl requests like the mai…

### PR DESCRIPTION
**Pull request by rasharab**
…n cocoapods repository

### CODE REVIEW

**Comment by rasharab** [comment]
When we attempted to use cocoapods-art in our continuous integration environment it killed our customer builds because the plugin was overriding the default behavior of cocoapods. It was forcing the usage of "-n" rather than "-netrc-optional".

The cocoapods community had moved away from the "-n" option a while back, and yet this plugin was still using it.
https://github.com/CocoaPods/cocoapods-downloader/pull/56/commits/e18994714d4d69d3cd99f3f05e8dfc618dc11af2

The larger point I'd like to make is that the way this plugin is currently architected is that, in overriding cocoapods default download behavior, it introduces the possibility that the code is outdated (as in this case).

My recommendation, if possible, is to completely remove the Downloader override behaviour in your plugin.

-Rashin

**Comment by kylefowler** [comment]
Does anyone monitor this repo anymore? Wed love to have this fix merged.

**Comment by eyalbe4** [comment]
My apologies for the late response. We'll review this pull request shortly.

**Comment by eyalbe4** [comment]
@rasharab,
Thanks for contributing this fix. This PR should have been merged a long time ago.
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by marchinram** [comment]
@eyalbe4 We really need this pr merged and the gem updated, so if I sign the CLA can I take over this pr or just create a new one and then you can merge?

**Comment by eyalbe4** [comment]
Absolutely @marchinram.
If you can create a new pull request and sign the [CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) we'll make sure to merge it and publish a new release quickly.

**Comment by eyalbe4** [comment]
Closing this one following the merge of https://github.com/JFrogDev/cocoapods-art/pull/19.

**Pull request closed without merging**
